name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install
      - run: npm run build
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.sudoku_username }}
